trigger: none


pool: myfirstpipelineagent

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'connection1'
    backendAzureRmStorageAccountName: 'tanvistorage1'
    backendAzureRmContainerName: 'tanvicontainer1'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'connection1'


